### PR TITLE
✨ feat: Utility for discord timestamps

### PR DESCRIPTION
**Pull request by Yaikava**
I think this could be helpful to others.

### CODE REVIEW

**Review by itohatweb — CHANGES_REQUESTED** [review]
I would say also allow UNIX timestamps. And maybe add a default format.

**Comment by Yaikava** [comment]
> I would say also allow UNIX timestamps. And maybe add a default format.

Which format should be default?

**Comment by itohatweb** [comment]
I guess just the one Discord uses as default too

**Comment by Yaikava** [comment]
Done, default format is handled by not including the format which makes discord show the default one.

**Review by Skillz4Killz — APPROVED** [review]

**Review by itohatweb — APPROVED** [review]

**Pull request merged**
